# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Node.js Package to GitHub Packages

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: 'Setup .yarnrc.yml'
        run: |
          yarn config set npmScopes.DevMountain.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.DevMountain.npmAlwaysAuth true
          yarn config set npmScopes.DevMountain.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn install --frozen-lockfile
      - run: yarn publish
